import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Link } from "react-scroll";
import { FiMenu } from "react-icons/fi";
import { MdClose } from "react-icons/md";
import { FaFacebookF, FaYoutube, FaInstagram } from "react-icons/fa";
import { logo } from "../assets";
import { navLinksdata } from "../constants";
const Navbar = () => {
    const [showMenu, setShowMenu] = useState(false);
    return (_jsxs("div", { className: "w-full h-24 sticky top-0 z-50 backdrop-blur-2xl transition-colors bg-bodyColor/70 mx-auto flex justify-between items-center font-titleFont border-b-[1px] border-b-gray-600 px-4", children: [_jsx("div", { children: _jsx("img", { src: logo, alt: "logo" }) }), _jsxs("div", { children: [_jsx("ul", { className: "hidden mdl:inline-flex items-center gap-6 lg:gap-10", children: navLinksdata.map(({ _id, title, link }) => (_jsx("li", { className: "text-base font-normal text-gray-400 tracking-wide cursor-pointer hover:text-designColor duration-300", children: _jsx(Link, { activeClass: "active", to: link, spy: true, smooth: true, offset: -70, duration: 500, children: title }) }, _id))) }), _jsx("span", { onClick: () => setShowMenu(!showMenu), className: "text-xl mdl:hidden bg-black w-10 h-10 inline-flex items-center justify-center rounded-full text-designColor cursor-pointer", children: _jsx(FiMenu, {}) }), showMenu && (_jsx("div", { className: "w-[80%] h-screen mdl:hidden overflow-scroll absolute top-0 left-0 bg-gray-900 p-4 scrollbar-hide", children: _jsxs("div", { className: "flex flex-col gap-8 py-2 relative", children: [_jsxs("div", { children: [_jsx("img", { className: "w-32", src: logo, alt: "logo" }), _jsx("p", { className: "text-sm text-gray-400 mt-2", children: "Bringing smiles one surgery at a time" })] }), _jsx("ul", { className: "flex flex-col gap-4", children: navLinksdata.map((item) => (_jsx("li", { className: "text-base font-normal text-gray-400 tracking-wide cursor-pointer hover:text-designColor duration-300", children: _jsx(Link, { onClick: () => setShowMenu(false), activeClass: "active", to: item.link, spy: true, smooth: true, offset: -70, duration: 500, children: item.title }) }, item._id))) }), _jsxs("div", { className: "flex flex-col gap-4", children: [_jsx("h2", { className: "text-base uppercase font-titleFont mb-4", children: "Find us at" }), _jsxs("div", { className: "flex gap-4", children: [_jsx("a", { href: "https://youtu.be/_dih2JOb2C8", target: "_blank", children: _jsx("span", { className: "bannerIcon", children: _jsx(FaYoutube, {}) }) }), _jsx("a", { href: "https://www.instagram.com/mountelizabethhospitals/p/C0d2R7lInFg/?next=%2Frubykantor%2F&hl=ja&img_index=1", target: "_blank", children: _jsx("span", { className: "bannerIcon", children: _jsx(FaInstagram, {}) }) }), _jsx("a", { href: "https://www.facebook.com/watch/?v=1032449527847176", target: "_blank", children: _jsx("span", { className: "bannerIcon", children: _jsx(FaFacebookF, {}) }) })] })] }), _jsx("span", { onClick: () => setShowMenu(false), className: "absolute top-4 right-4 text-gray-400 hover:text-designColor duration-300 text-2xl cursor-pointer", children: _jsx(MdClose, {}) })] }) }))] })] }));
};
export default Navbar;
